server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/singularity_order?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

rocketmq:
  name-server: localhost:9876
  producer:
    group: order-producer-group
